export const LOGO_PATH = '/assets/BoP.jpg';
export const BANNER_PATH = '/assets/Banner__1_.jpg';
export const PLACEHOLDER_LOGO = 'https://placehold.co/128x128/1a1a1a/amber?text=Token';

export const MOCK_TOKENS = [
  {
    id: 1,
    name: "Board of Peace",
    ticker: "BOP",
    tagline: "United Stewards on XRPL – Join the Harmony",
    description: "Born from the Potheads XRP community in 2017, Board of Peace represents a collective of XRPL enthusiasts united by peace through art, cryptocurrency, and meaningful impact.",
    issuer: "rGF1o7dsC776Hov8qKkPCN1wkVh18sz5bf",
    supply: "1,000,000,000",
    holders: "2,847",
    trustLines: "3,124",
    badges: ["Verified", "Featured", "OG"],
    category: "Social",
    views: 15420,
    comments: 89,
    logoUrl: "/assets/BoP.jpg",
    bannerUrl: "/assets/Banner__1_.jpg",
    website: "https://boardofpeace.com",
    twitter: "",
    discord: "",
    telegram: "",
    github: "",
    whitepaper: "",
    mediaUrls: ["/assets/Banner__1_.jpg"],
    roadmap: [
      { title: "Q1 2024 - Foundation", description: "Community launch and initial token distribution." },
      { title: "Q2 2024 - Growth", description: "Partnerships with XRPL projects and charity initiatives." },
      { title: "Q3 2024 - Expansion", description: "NFT collection and art collaborations." },
    ],
    team: [{ name: "Potheads XRP", role: "Founder", avatar: null }],
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: 2,
    name: "Peace Ducks",
    ticker: "DUCK",
    tagline: "What the Duck! Meme meets meaning",
    description: "Community meme token with charitable impact.",
    issuer: "rN7n7otQDd6FczFgLdJqcdNCood2aR74h8",
    supply: "500,000,000",
    holders: "1,523",
    trustLines: "1,890",
    badges: ["New", "Meme"],
    category: "Meme",
    views: 8930,
    comments: 45,
    logoUrl: null,
    bannerUrl: null,
    website: "",
    twitter: "",
    discord: "",
    telegram: "",
    github: "",
    whitepaper: "",
    mediaUrls: [],
    roadmap: [],
    team: [],
    createdAt: "2025-01-20T00:00:00Z",
  },
  {
    id: 3,
    name: "Harmony Arts",
    ticker: "HART",
    tagline: "NFT collective for global peace",
    description: "Artist collective creating NFTs for charity.",
    issuer: "rBTwLga3i2gz3doX6Gva3MgEV8ZCD8jjQH",
    supply: "100,000,000",
    holders: "892",
    trustLines: "1,234",
    badges: ["Verified"],
    category: "NFT",
    views: 6780,
    comments: 34,
    logoUrl: null,
    bannerUrl: null,
    website: "",
    twitter: "",
    discord: "",
    telegram: "",
    github: "",
    whitepaper: "",
    mediaUrls: [],
    roadmap: [],
    team: [],
    createdAt: "2024-06-10T00:00:00Z",
  },
];

export const CATEGORIES = ["DeFi", "NFT", "Gaming", "Charity", "Utility", "Social", "Meme"];
